---
- name: "Waybar | Install waybar"
  ansible.builtin.pacman:
    name: waybar
    state: present
  become: true

- name: "Waybar | Sync dots"
  ansible.posix.synchronize:
    dest: "{{ ansible_user_dir }}/.config/"
    src: waybar

- name: "Waybar | Activate waybar.service"
  ansible.builtin.systemd_service:
    name:     "waybar.service"
    state:    "started"
    enabled:  "true"
    scope:    "user"
