---
- name: "Wlogout | Install wlogout"
  ansible.builtin.pacman:
    name: wlogout
    state: present
  become: true

- name: "Wlogout | Sync dots"
  ansible.posix.synchronize:
    dest: "{{ ansible_user_dir }}/.config/"
    src: wlogout
