---
- name: "System | Update pacman"
  community.general.pacman:
    update_cache: true
    upgrade: true
    state: latest
  become: true

- name: "System | Set hosts"
  ansible.builtin.template:
    dest: "/etc/hosts"
    src: hosts.j2
    mode: "0644"
  become: true

- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'

- name: "System | install system necessities"
  ansible.builtin.pacman:
    name:
      - brightnessctl
      - pacman-contrib
      - nano
      - rsync
      - libnotify
      - parallel
      - cmake
      - pamixer
      - pavucontrol
      - wireplumber
      - gst-plugin-pipewire
      - pipewire-pulse
      - pipewire-jack
      - pipewire-audio
      - pipewire-alsa
      - pipewire-alsa
      - udiskie
      - bluez-utils
      - bluez
      - network-manager-applet
      - networkmanager 
      - nextcloud-client
      - blueman 
    state: present
  become: true

- name: "Scripts | Sync scripts"
  ansible.posix.synchronize:
    dest: "{{ ansible_user_dir }}/.config/"
    src: scripts
